name: Forest Reservation Checker

on:
  schedule:
    - cron: "*/3 * * * *"  # 3분마다 실행
  workflow_dispatch:        # 수동 실행 가능

jobs:
  check-reservations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install puppeteer@21 node-telegram-bot-api

      - name: Run checker
        run: node scripts/check.js
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
