name: Forest Reservation Checker

on:
  schedule:
    - cron: "*/3 * * * *" # 3분마다 실행
  workflow_dispatch:

jobs:
  check-reservations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache Puppeteer Chromium
        uses: actions/cache@v4
        with:
          path: ~/.cache/puppeteer
          key: puppeteer-cache

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install puppeteer@22 node-telegram-bot-api

      - name: Run checker
        run: node scripts/check.js
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshots
          path: |
            error-*.png
